---
remote_theme: jekyll/minima
title: OmniTangent
google_analytics: G-S4NDZ0GWCT
utterances:
  repo: "ztangents/ztangents"
  issue-term: "pathname"
  label: "utteranc.es"
  theme: "github-light"
---
